### ISSUE TITLE
Initial features

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/thinkgpt#1]
- [x] Knowledge learning using long memory and in context learning
Make the LLM aware that it has a long memory
Tell it to perform a remember action
Expose an interface to teach or store information (alternatively, tell it to extract rules from the context and generate a description for the information to be used in indexing)
Examples:
Teach it about docarray v2 semantics
Teach it about langchain...
Also make sure the LLM is aware of the whole memory structute/schema and let it utilize the full retrieval api
Also increase the context length of gpt by telling it that you want to process information using an LLM but it has limited context and prompt it to either summarize the long context and split it into further splits and process chunk by chunk
- [x] Divide and conquer applied to LLMs to divide big tasks into sub tasks
- [x] Conditional selects
- [x] LLM reflection component like in generative agents paper
- [x] Self healing code gen

**Comment by ericries** [comment]
Super cool-looking project!

I'm interested in the addition of fine-tuning, I think that'd be pretty useful
